### PR TITLE
allows to set size in percent

### PR DESCRIPTION
**Pull request by gonimar**

### CODE REVIEW

**Comment by tonydspaniard** [comment]
@gonimar mind fixing conflicts? Is this also related to #19 ?

**Comment by gonimar** [comment]
yes

**Comment by bzz445** [comment]
:+1:

**Comment by gonimar** [comment]
bump

**Comment by tonydspaniard** [comment]
@gonimar apologies for the late reply... do you mind to fix the conflicts? will merge

**Comment by tonydspaniard** [comment]
@gonimar no need. i am adding your changes my self. Thanks for your work.

**Comment by tonydspaniard** [comment]
added here: https://github.com/2amigos/yii2-leaflet-extension/commit/05edce3e5a70d4ac73a76571d35c4779d41f1b0c

**Pull request closed without merging**
